#!/bin/bash
set -e

aks-engine deploy \
  --auth-method client_secret \
  --client-id $AZURE_CLIENT_ID \
  --client-secret $AZURE_CLIENT_SECRET \
  --subscription-id $AZURE_SUBSCRIPTION_ID \
  --dns-prefix $AKS_DNS_PREFIX \
  --resource-group $AZURE_RESOURCE_GROUP \
  --location $AZURE_LOCATION \
  --api-model /config/models/k8s-azurenet.json \
  -o /output/$AKS_DNS_PREFIX


spotinst-aks-engine import\
  --resource-group $AZURE_RESOURCE_GROUP \
  --output-directory /output/$AKS_DNS_PREFIX \
  --subscription $AZURE_SUBSCRIPTION_ID \
  --set capacity.maximum=3 \
  --set capacity.target=2
